// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Itl0ftCwUtwLFp9y2LYbE2ELZH_xfBQ',
    appId: '1:706931350804:web:b3857c68ffd618f5213601',
    messagingSenderId: '706931350804',
    projectId: 'chat-app-new-85411',
    authDomain: 'chat-app-new-85411.firebaseapp.com',
    storageBucket: 'chat-app-new-85411.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIHHVi5qE1RIMPDZZ0XkfO3LB92pE0po',
    appId: '1:706931350804:android:8663c71438283f82213601',
    messagingSenderId: '706931350804',
    projectId: 'chat-app-new-85411',
    storageBucket: 'chat-app-new-85411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfOljgynlFiF7YX7eW5mFe0DuhL9wRmgY',
    appId: '1:706931350804:ios:58a6efa6580784d5213601',
    messagingSenderId: '706931350804',
    projectId: 'chat-app-new-85411',
    storageBucket: 'chat-app-new-85411.firebasestorage.app',
    iosBundleId: 'com.example.chatAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfOljgynlFiF7YX7eW5mFe0DuhL9wRmgY',
    appId: '1:706931350804:ios:58a6efa6580784d5213601',
    messagingSenderId: '706931350804',
    projectId: 'chat-app-new-85411',
    storageBucket: 'chat-app-new-85411.firebasestorage.app',
    iosBundleId: 'com.example.chatAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Itl0ftCwUtwLFp9y2LYbE2ELZH_xfBQ',
    appId: '1:706931350804:web:f766b953c9750bbe213601',
    messagingSenderId: '706931350804',
    projectId: 'chat-app-new-85411',
    authDomain: 'chat-app-new-85411.firebaseapp.com',
    storageBucket: 'chat-app-new-85411.firebasestorage.app',
  );
}
